### ISSUE TITLE
Netty Error about old version

### ISSUE THREAD

**Issue by MarchLiu** [benfb/lein-gorilla#1]
when run gorilla with java 11 and Leiningen, a error received:
`Gorilla-REPL: 0.5.3
Started nREPL server on port 50888
Running at http://127.0.0.1:50890/worksheet.html .
Ctrl+C to exit.
Sun Jan 06 02:35:12 CST 2019 [client-loop] ERROR - select exception, should not happen
java.lang.IllegalStateException: Client/Server mode has not yet been set.
	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:98)
	at org.httpkit.client.HttpClient.finishConnect(HttpClient.java:395)
	at org.httpkit.client.HttpClient.run(HttpClient.java:472)
	at java.base/java.lang.Thread.run(Thread.java:834)
Sun Jan 06 02:35:12 CST 2019 [client-loop] ERROR - select exception, should not happen
java.lang.IllegalStateException: Client/Server mode has not yet been set.
	at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:98)
	at org.httpkit.client.HttpClient.finishConnect(HttpClient.java:395)
	at org.httpkit.client.HttpClient.run(HttpClient.java:472)
	at java.base/java.lang.Thread.run(Thread.java:834)
`
and gorilla could run else good.
The error maybe like [https://stackoverflow.com/questions/9536063/running-netty-3-3-1-final-secure-chat-example-out-of-the-box-gives-error-client](https://stackoverflow.com/questions/9536063/running-netty-3-3-1-final-secure-chat-example-out-of-the-box-gives-error-client) so need more newer  Netty more than 3.4 ?

**Comment by MarchLiu** [comment]
This error is't occur every time.

**Comment by jdf-id-au** [comment]
I'm getting this with jdk1.8.0_202 and lein-gorilla 0.6.0. Something to do with the way `check-for-update` calls `http/get` I think.

Can be avoided with```:gorilla-options {:phone-home false}``` in `project.clj`.
